# Generated by Django 4.2.3 on 2023-07-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(max_length=128, verbose_name="지갑주소"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="국가코드"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="이메일"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="이름"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="성"
                    ),
                ),
                ("sso_type", models.CharField(max_length=16, verbose_name="SSO 타입")),
            ],
        ),
    ]
