# Generated by Django 4.2.3 on 2023-07-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(max_length=128, unique=True, verbose_name="지갑주소"),
        ),
    ]
