# Generated by Django 4.2.3 on 2023-07-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_wallet_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user", options={"verbose_name": "사용자", "verbose_name_plural": "사용자"},
        ),
    ]
