# Generated by Django 4.2.3 on 2023-08-07 17:57

from django.db import migrations, models
import utils.common


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="info",
            field=models.TextField(blank=True, null=True, verbose_name="추가정보"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.common.upload_file_to_s3,
                verbose_name="프로필 이미지",
            ),
        ),
    ]
