# Generated by Django 4.2.3 on 2023-09-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="유저닉네임"
            ),
        ),
    ]
