# Generated by Django 4.2.3 on 2023-07-22 22:11

from django.db import migrations, models
import utils.common


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="이름")),
                ("symbol", models.CharField(max_length=32, verbose_name="심볼")),
                (
                    "cover_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.common.upload_file_to_s3,
                        verbose_name="커버 이미지",
                    ),
                ),
                (
                    "contract_address",
                    models.CharField(max_length=128, verbose_name="컨트랙트 주소"),
                ),
                ("description_ko", models.TextField(verbose_name="설명(한글)")),
                ("description_en", models.TextField(verbose_name="설명(영어)")),
                ("slug", models.SlugField(max_length=128, verbose_name="슬러그")),
                (
                    "type",
                    models.CharField(
                        choices=[("MUSIC", "MUSIC"), ("TICKET", "TICKET")],
                        max_length=32,
                        verbose_name="컨트랙트 타입",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "컨트랙트", "verbose_name_plural": "컨트랙트",},
        ),
    ]
