# Generated by Django 4.2.3 on 2023-08-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_transaction_nonce_alter_transaction_from_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="from_address",),
        migrations.RemoveField(model_name="transaction", name="status",),
        migrations.AddField(
            model_name="transaction",
            name="func",
            field=models.IntegerField(blank=True, null=True, verbose_name="Function명"),
        ),
    ]
