# Generated by Django 4.2.3 on 2023-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_remove_transaction_from_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="func",
            field=models.CharField(blank=True, null=True, verbose_name="Function명"),
        ),
    ]
