# Generated by Django 4.2.3 on 2023-08-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0008_alter_token_stock"),
        ("contracts", "0006_alter_transaction_func"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="tokens.token",
                verbose_name="토큰",
            ),
        ),
    ]
