# Generated by Django 4.2.3 on 2023-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_transaction_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="to_address",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="받는 주소(creator)"
            ),
        ),
    ]
