# Generated by Django 4.2.3 on 2023-08-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("contracts", "0008_alter_transaction_to_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="orders.order",
                verbose_name="주문",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_address",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="받는 주소"
            ),
        ),
    ]
