# Generated by Django 4.2.3 on 2023-08-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_transaction_order_alter_transaction_to_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tx_status",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="트랜잭션 상태"
            ),
        ),
    ]
