# Generated by Django 4.2.3 on 2023-08-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_transaction_tx_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="func",
            field=models.CharField(blank=True, null=True, verbose_name="Function"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_price",
            field=models.FloatField(blank=True, null=True, verbose_name="가스 가격(gwei)"),
        ),
    ]
