# Generated by Django 4.2.3 on 2023-10-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0011_alter_transaction_func_alter_transaction_gas_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verifier_code",
                    models.CharField(max_length=128, verbose_name="검증자 코드"),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "registered",
                    models.BooleanField(default=False, verbose_name="등록 여부"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifiers",
                        to="contracts.contract",
                        verbose_name="컨트랙트",
                    ),
                ),
            ],
            options={"verbose_name": "검증자", "verbose_name_plural": "검증자",},
        ),
        migrations.CreateModel(
            name="VerifiedTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="수량")),
                (
                    "wallet_address",
                    models.CharField(max_length=128, verbose_name="지갑주소"),
                ),
                (
                    "contract_address",
                    models.CharField(max_length=128, verbose_name="컨트랙트 주소"),
                ),
                ("nft_id", models.IntegerField(verbose_name="NFT ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_tickets",
                        to="redeems.verifier",
                        verbose_name="검증자",
                    ),
                ),
            ],
            options={"verbose_name": "검증된 티켓", "verbose_name_plural": "검증된 티켓",},
        ),
    ]
