# Generated by Django 4.2.3 on 2023-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("krw", "krw"), ("usd", "usd")],
                max_length=16,
                verbose_name="통화",
            ),
        ),
        migrations.AlterField(
            model_name="ordertoken",
            name="currency",
            field=models.CharField(
                choices=[("krw", "krw"), ("usd", "usd")],
                max_length=16,
                verbose_name="통화",
            ),
        ),
    ]
