# Generated by Django 4.2.3 on 2023-08-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_currency_alter_ordertoken_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("success", "success"),
                    ("refund", "refund"),
                    ("error", "error"),
                    ("cancel", "cancel"),
                ],
                max_length=32,
                verbose_name="주문상태",
            ),
        ),
    ]
