# Generated by Django 4.2.3 on 2023-07-16 21:19

from django.db import migrations, models
import django.db.models.deletion
import utils.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="이름")),
                ("symbol", models.CharField(max_length=32, verbose_name="심볼")),
                (
                    "cover_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.common.upload_file_to_s3,
                        verbose_name="커버 이미지",
                    ),
                ),
                (
                    "contract_address",
                    models.CharField(max_length=128, verbose_name="컨트랙트 주소"),
                ),
                ("description_ko", models.TextField(verbose_name="설명(한글)")),
                ("description_en", models.TextField(verbose_name="설명(영어)")),
                ("slug", models.SlugField(max_length=128, verbose_name="슬러그")),
                (
                    "type",
                    models.CharField(
                        choices=[("MUSIC", "MUSIC"), ("TICKET", "TICKET")],
                        max_length=32,
                        verbose_name="컨트랙트 타입",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "컨트랙트", "verbose_name_plural": "컨트랙트",},
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="이름")),
                (
                    "token_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.common.upload_file_to_s3,
                        verbose_name="토큰 이미지",
                    ),
                ),
                (
                    "animation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=utils.common.upload_file_to_s3,
                        verbose_name="애니메이션",
                    ),
                ),
                ("nft_id", models.IntegerField(verbose_name="NFT ID")),
                ("stock", models.IntegerField(verbose_name="재고(amout)")),
                ("price_krw", models.CharField(max_length=32, verbose_name="가격(KRW)")),
                ("price_usd", models.CharField(max_length=32, verbose_name="가격(USD)")),
                ("description_ko", models.TextField(verbose_name="설명(한글)")),
                ("description_en", models.TextField(verbose_name="설명(영어)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tokens.contract",
                        verbose_name="컨트랙트",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="사용자(creator)",
                    ),
                ),
            ],
            options={"verbose_name": "토큰", "verbose_name_plural": "토큰",},
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="에셋이름")),
                ("type", models.CharField(max_length=128, verbose_name="에셋타입")),
                (
                    "media",
                    models.FileField(
                        upload_to=utils.common.upload_file_to_s3, verbose_name="에셋 실제파일"
                    ),
                ),
                (
                    "download",
                    models.BooleanField(default=False, verbose_name="다운로드 가능여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tokens.token",
                        verbose_name="토큰",
                    ),
                ),
            ],
            options={"verbose_name": "에셋", "verbose_name_plural": "에셋",},
        ),
    ]
