# Generated by Django 4.2.3 on 2023-07-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="status",
            field=models.CharField(
                choices=[
                    ("PREPARE", "DB만 저장"),
                    ("MINTED", "실제 minting됨"),
                    ("ERROR", "minting error"),
                    ("BURN", "burn 됨"),
                    ("CANCEL", "취소됨"),
                ],
                default="PREPARE",
                max_length=32,
                verbose_name="상태",
            ),
        ),
    ]
