# Generated by Django 4.2.3 on 2023-07-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_token_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tokens.token",
                verbose_name="토큰",
            ),
        ),
    ]
