# Generated by Django 4.2.3 on 2023-07-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_alter_asset_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[
                    ("image", "image"),
                    ("music/mp3", "music/mp3"),
                    ("file", "file"),
                    ("video", "video"),
                    ("etc", "etc"),
                ],
                max_length=128,
                verbose_name="에셋타입",
            ),
        ),
    ]
