# Generated by Django 4.2.3 on 2023-07-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_wallet_address"),
        ("tokens", "0005_alter_token_nft_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="tokens.token",
                verbose_name="토큰",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to="tokens.contract",
                verbose_name="컨트랙트",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="users.user",
                verbose_name="사용자(creator)",
            ),
        ),
    ]
