# Generated by Django 4.2.3 on 2023-07-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("tokens", "0006_alter_asset_token_alter_token_contract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to="contracts.contract",
                verbose_name="컨트랙트",
            ),
        ),
        migrations.DeleteModel(name="Contract",),
    ]
